# Backend Node - Elasticsearch + Logstash Collector
# Deploy on: {YOUR_BACKEND_IP_1} (NetFlow) or {YOUR_BACKEND_IP_2} (sFlow)

version: "3.8"
services:
  es-remote:
    image: docker.elastic.co/elasticsearch/elasticsearch:${STACK_VERSION}
    container_name: es-remote
    volumes:
      - ./certs:/usr/share/elasticsearch/config/certs
      - data-remote:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
    cap_add: [IPC_LOCK]
    environment:
      - node.name=es-remote-${BACKEND_IP}
      - cluster.name=${CLUSTER_NAME}
      - node.roles=data,ingest
      - discovery.seed_hosts=${FRONTEND_IP}:9300,${FRONTEND_IP}:9301
      - network.publish_host=${BACKEND_IP}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - xpack.license.self_generated.type=${LICENSE}
      - bootstrap.memory_lock=true
      - xpack.security.enabled=true
      - xpack.security.http.ssl.enabled=true
      - xpack.security.http.ssl.key=certs/wildcard/wildcard.key
      - xpack.security.http.ssl.certificate=certs/wildcard/wildcard.crt
      - xpack.security.http.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.enabled=true
      - xpack.security.transport.ssl.key=certs/wildcard/wildcard.key
      - xpack.security.transport.ssl.certificate=certs/wildcard/wildcard.crt
      - xpack.security.transport.ssl.certificate_authorities=certs/ca/ca.crt
      - xpack.security.transport.ssl.verification_mode=certificate
      - xpack.security.http.ssl.verification_mode=certificate
    mem_limit: ${MEM_LIMIT}
    ulimits:
      memlock: { soft: -1, hard: -1 }

  logstash:
    build:
      context: .
      dockerfile: Dockerfile-logstash
    container_name: logstash-flow
    # Using host network to see real Source IPs
    network_mode: host
    command: /usr/share/logstash/bin/logstash -f /usr/share/logstash/pipeline/logstash-unified.conf
    volumes:
      - ./logstash-unified.conf:/usr/share/logstash/pipeline/logstash-unified.conf
      - ./certs/ca/ca.crt:/usr/share/logstash/ca.crt
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - FRONTEND_IP=${FRONTEND_IP}
      - ELASTICSEARCH_HOST=localhost
      - QUEUE_TYPE=persisted
      - QUEUE_MAX_BYTES=1gb
    depends_on:
      - es-remote

volumes:
  data-remote:
    driver: local
