input {
  # NetFlow
  udp {
    port => 2050
    type => "netflow"
    codec => netflow
    receive_buffer_bytes => 16777216
    workers => 4
  }
  # sFlow
  udp {
    port => 6343
    type => "sflow"
    codec => sflow
    receive_buffer_bytes => 16777216
    workers => 4
  }
}

filter {
  if [type] == "netflow" {
    mutate {
      add_field => {
        "[event][type]" => "netflow"
        "[device][name]" => "juniper-sw"
        "[device][ip]" => "10.4.4.93"
        "[agent][name]" => "logstash-collector"
        "[agent][type]" => "logstash"
      }
    }
    mutate {
      rename => {
        "[netflow][ipv4_src_addr]" => "[source][ip]"
        "[netflow][ipv4_dst_addr]" => "[destination][ip]"
        "[netflow][l4_src_port]"   => "[source][port]"
        "[netflow][l4_dst_port]"   => "[destination][port]"
        "[netflow][protocol]"      => "[network][iana_number]"
        "[netflow][input_snmp]"    => "[observer][ingress][interface][id]"
        "[netflow][output_snmp]"   => "[observer][egress][interface][id]"
      }
    }
    ruby {
      code => "
        fb = event.get('[netflow][in_bytes]').to_i
        fp = event.get('[netflow][in_pkts]').to_i
        event.set('[network][bytes]', fb * 4096)
        event.set('[network][packets]', fp * 4096)
        event.set('[source][bytes]', fb * 4096)
        event.set('[source][packets]', fp * 4096)
      "
    }
  } else if [type] == "sflow" {
    mutate {
      add_field => {
        "[event][type]" => "sflow"
        "[device][name]" => "cisco-nexus"
        "[agent][name]" => "logstash-collector"
        "[agent][type]" => "logstash"
      }
    }
    if [sflow][agent_ip] { mutate { copy => { "[sflow][agent_ip]" => "[device][ip]" } } }
    if [sflow][src_ip] { mutate { copy => { "[sflow][src_ip]" => "[source][ip]" } } }
    if [sflow][dst_ip] { mutate { copy => { "[sflow][dst_ip]" => "[destination][ip]" } } }
  }

  mutate {
    convert => {
      "[network][iana_number]" => "integer"
      "[source][port]"         => "integer"
      "[destination][port]"    => "integer"
    }
  }
}

output {
  elasticsearch {
    hosts => ["https://es-remote:9200"]
    user => "elastic"
    password => "${ELASTIC_PASSWORD}"
    ssl_enabled => true
    ssl_verification_mode => "none"
    index => "logstash-flow-%{+YYYY.MM.dd}"
  }
}
